apiVersion: v1
kind: Service
metadata:
  name: msc-api-web-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 8008
    # static port when accessing on of nodes externally
      nodePort: 30777
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: msc-api-web-pod
