apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-service
  name: redis-service
spec:
  ports:
    # the port that this service should serve on
    - port: 6379
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: redis-pod
