apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
spec:
  containers:
    -
      image: mongo
      name: mongo
      ports:
        -
          name: mongo
          containerPort: 27017
          hostPort: 27017
