# values should be encoded:
# echo "secret" | base64
# in this example, REDIS_HOST is redis-service, REDIS_PORT is 6379
# secrets may be encoded:
# echo "cmVkaXMtc2VydmljZQo=" | base64 -D
# see spec for more info http://kubernetes.io/docs/user-guide/secrets/

apiVersion: v1
kind: Secret
metadata:
  name: msc-api-web-redis
type: Opaque
data:
  redishost: cmVkaXMtc2VydmljZQo=
  redisport: NjM3OQo=
