apiVersion: v1
kind: ReplicationController
metadata:
  name: msc-web-controller
spec:
  replicas: 2
  selector:
    name: msc-web-pod
  template:
    metadata:
      name: msc-web-pod
      labels:
        name: msc-web-pod
    spec:
      containers:
        - name: msc-web
          image: dlouchansky/msc-web
          ports:
            - containerPort: 80
