apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq-admin-service
  name: rabbitmq-admin-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 15672
    # static port when accessing on of nodes externally
      nodePort: 30772
  selector:
    name: rabbitmq-pod
