apiVersion: v1
kind: ReplicationController
metadata:
  name: msc-companies-controller
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    name: msc-companies-pod
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      name: msc-companies-pod
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: msc-companies-pod
    spec:
      containers:
        - name: msc-companies
          image: dlouchansky/msc-companies
          env:
            -
              name: "RABBIT_MQ_ADDRESS"
              value: "rabbitmq-service"
            -
              name: "RABBIT_MQ_USER"
              value: "mysql"
            -
              name: "RABBIT_MQ_PASSWORD"
              value: "sample"
            -
              name: "SERVICE_PORT"
              value: "8008"
            -
              name: "MYSQL_PASSWORD"
              value: "mysql"
            -
              name: "MYSQL_USER"
              value: "mysql"
            -
              name: "MYSQL_HOST"
              value: "mysql-service"
            -
              name: "MYSQL_DB"
              value: "sample"
            -
              name: "STATS_SERVICE"
              value: "stats-service"

          ports:
            - containerPort: 8008
